targets:
  $default:
    builders:
      pinterest|a_json_property:
        generate_for:
          - lib/src/models.dart

builders:
  a_json_property:
    import: "package:pinterest/builder.dart"
    builder_factories: ["aJsonProperty"]
    build_extensions: {".dart": ["models.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
