targets:
  $default:
    builders:
      pinterest|json_property:
        generate_for:
          - lib/src/models.dart

builders:
  json_property:
    import: "package:pinterest/builder.dart"
    builder_factories: ["jsonProperty"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
